server:
  port: 8081

spring:
  profiles:
    active: local

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

app:
  tmdb:
    bearer-token: ${TMDB_BEARER_TOKEN:}
